### ISSUE TITLE
Deprecation warning fixes

### ISSUE THREAD

**Issue by nethad** [manuelvanrijn/bootstrap-switch-rails#14]
Hi,

do you plan to release a new version for this gem? This would remove the deprecation warnings already fixed in master.

**Comment by manuelvanrijn** [comment]
Hi @nethad,

I'd like to keep the versions equal to the javascript plugin, so as soon as there's a new version :)

**Comment by webhive** [comment]
Hmm - it doesn't looks logical. Rails (or sass or something else) can bring some breaking changes and it will make you gem completely broken, but you will sit and wait for js plugin version change :( This is first order rails gem so IMHO should reflect rails changes too.

**Comment by manuelvanrijn** [comment]
@webhive this isn't a breaking change, however I just pushed version 3.3.3 with the fix.

My main goal was to reflect the version of the gem with the version of the javascript library, but that was just a thought I'm willing to let go

**Comment by webhive** [comment]
Thank you for update! I see your naming idea. I just think this is hard or even impossible to reflect version only of one side of gem (js) and ignore other side (rails).

**Comment by nethad** [comment]
@manuelvanrijn Thank you!
