### ISSUE TITLE
Cannot read property 'apply' of undefined 

### ISSUE THREAD

**Issue by wonderer007** [manuelvanrijn/bootstrap-switch-rails#15]
I am applying bootstrap switch with options like this
$('#switch-state').bootstrapSwitch('setSizeClass', 'switch-mini');
its throwing this error
Uncaught TypeError: Cannot read property 'apply' of undefined

**Comment by manuelvanrijn** [comment]
please assign javascript issues to the main project: https://github.com/nostalgiaz/bootstrap-switch
