### ISSUE TITLE
Depreciation Warning

### ISSUE THREAD

**Issue by Okomikeruko** [manuelvanrijn/bootstrap-switch-rails#18]
I've started getting the following warning when I use your gem. 

`DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /usr/local/rvm/gems/ruby-2.2.5/gems/bootstrap-switch-rails-3.0.0/vendor/assets/stylesheets/bootstrap3-switch.css.scss to /usr/local/rvm/gems/ruby-2.2.5/gems/bootstrap-switch-rails-3.0.0/vendor/assets/stylesheets/bootstrap3-switch.scss. (called from _app_views_layouts_blank_html_erb__1211379351604111721_92167400 at /home/ubuntu/workspace/law_dasher/app/views/layouts/blank.html.erb:5)`

**Comment by manuelvanrijn** [comment]
is already fixed :)
