### ISSUE TITLE
Bootstrap 4 usage in 3.3.4

### ISSUE THREAD

**Issue by cmcguff** [manuelvanrijn/bootstrap-switch-rails#21]
Can you clarify the correct settings to use for Bootstrap 4?

Seems like I can only switch css between bootstrap2 and bootstrap3, do I use bootstrap3-switch for bootstrap4 or something different?

application.js
`
//= require bootstrap-switch
`
application.scss
`
@import "bootstrap3-switch";
`

**Comment by manuelvanrijn** [comment]
Hi @cmcguff 

The plugin being used (https://github.com/Bttstrp/bootstrap-switch) only supports bootstrap 2 and bootstrap 3. I think you have to look for an alternative (maybe: https://gitbrent.github.io/bootstrap4-toggle/)

Good luck!
